#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController